### ISSUE TITLE
java.lang.NoClassDefFoundError 1.7.x-3

### ISSUE THREAD

**Issue by SvEgiiVEteR** [MrIbby/BabyAnimals#3]
http://pastebin.com/8CY5pKXG
Forge 10.13.4.1492
Java 7
Baby Animals 1.7.10-3

**Comment by coolacid** [comment]
Any update?

**Comment by MrIbby** [comment]
You are using Baby Animals Model Swapper v1.7.10-3, which is an alpha version.

The latest recommended version is v1.7.10-2, found here: http://minecraft.curseforge.com/projects/baby-animals-model-swapper/files/2229254

**Comment by MrIbby** [comment]
Addressed in 854ad77f4804486bbaa83fff1618da3036b53683. Will release update very soon.

**Comment by MrIbby** [comment]
Fixed in [Baby Animals Model Swapper 1.7.10-4](https://minecraft.curseforge.com/projects/baby-animals-model-swapper/files/2437280/download).
